services:
    _defaults:
        autowire: true
        autoconfigure: true

    MadeYourDay\RockSolidColumns\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,MadeYourDay,Resources}'
